name: Lint and prettier

on: [pull_request]

jobs:
  lintAndPrettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 17.0.1
      - name: Install dependencies frontend
        working-directory: ./frontend
        run: yarn install --frozen-lockfile
      - name: Install dependencies backend
        working-directory: ./backend
        run: yarn install --frozen-lockfile
      - name: Run lint
        run: yarn lint
      - name: Run prettier
        run: yarn prettier
