import { tournamentStyles } from '../constants';

export const blocks = [
  {
    blockId: 12,
    startTime: null,
    persons: 3,
    dayId: null,
    areaId: null,
    style: tournamentStyles[0],
    age: 'Mladší junioři',
    category: 'Novorozenci Znojmo',
    customParameter: '20 kg',
    sex: 'M',
    sportId: 1,
    tournamentId: 1,
  },
  {
    blockId: 1,
    startTime: 120,
    persons: 5,
    dayId: 1,
    areaId: 1,
    style: tournamentStyles[0],
    age: 'Mladší junioři',
    category: 'Tuřňáci Litvínov',
    customParameter: '100 kg',
    sex: 'M',
    sportId: 1,
    tournamentId: 1,
  },
  {
    blockId: 2,
    startTime: 300,
    persons: 2,
    dayId: 1,
    areaId: 1,
    style: tournamentStyles[0],
    age: 'Starší junioři',
    category: 'Bloncky Cheb',
    customParameter: '60 kg',
    sex: 'F',
    sportId: 1,
    tournamentId: 1,
  },
  {
    blockId: 3,
    startTime: 360,
    persons: 4,
    dayId: 1,
    areaId: 1,
    style: tournamentStyles[0],
    age: 'Starší junioři',
    category: 'Vraci Aš',
    customParameter: '40 kg',
    sex: 'M',
    sportId: 2,
    tournamentId: 1,
  },
  {
    blockId: 4,
    startTime: 200,
    persons: 3,
    dayId: 1,
    areaId: 1,
    style: tournamentStyles[0],
    age: 'Dospělí',
    category: 'Chomutov SUV',
    customParameter: '90 kg',
    sex: 'M',
    sportId: 1,
    tournamentId: 1,
  },
  {
    blockId: 5,
    startTime: 100,
    persons: 2,
    dayId: 1,
    areaId: 2,
    style: tournamentStyles[0],
    age: 'Mladší junioři',
    category: 'Holoubátka Praha',
    customParameter: '50 kg',
    sex: 'F',
    sportId: 2,
    tournamentId: 1,
  },
  {
    blockId: 6,
    startTime: 180,
    persons: 8,
    dayId: 1,
    areaId: 2,
    style: tournamentStyles[0],
    age: 'Starší junioři',
    category: 'Ospalci Brno',
    customParameter: '70 kg',
    sportId: 2,
    tournamentId: 1,
  },
  {
    blockId: 7,
    startTime: 240,
    persons: 4,
    dayId: 1,
    areaId: 2,
    style: tournamentStyles[0],
    age: 'Starší junioři',
    category: 'ROG Liberec',
    customParameter: undefined,
    sex: 'M',
    sportId: 1,
    tournamentId: 1,
  },
  {
    blockId: 8,
    startTime: 300,
    persons: 3,
    dayId: 2,
    areaId: 2,
    style: tournamentStyles[0],
    age: 'Dospělí',
    category: 'Lvice Praha',
    customParameter: '70 kg',
    sex: 'F',
    sportId: 1,
    tournamentId: 1,
  },
];

export const areas = [
  {
    areaId: 1,
    name: 'Velká hala',
    tournamentId: 1,
  },
  {
    areaId: 2,
    name: 'Malá hala',
    tournamentId: 1,
  },
];

export const days = [
  {
    dayId: 1,
    date: '2022-01-01',
    description: 'Rozřazovací kolo',
    startTime: 100,
    endTime: 400,
    tournamentId: 1,
  },
  {
    dayId: 2,
    date: '2022-01-02',
    description: 'Dolní část tabulky',
    startTime: 100,
    endTime: 400,
    tournamentId: 1,
  },
];

export const sports = [
  {
    sportId: 1,
    name: 'Skok do dálky',
  },
  {
    sportId: 2,
    name: 'Běh na 100 m',
  },
];

export const tournaments = [
  {
    tournamentId: 1,
    name: 'Mistrovství ČR',
    location: 'Praha',
    startDate: '2022-01-01',
    endDate: '2022-01-15',
    userId: 1,
  },
  {
    tournamentId: 2,
    name: 'Závody velkých kluků',
    location: 'Brno',
    startDate: '2022-01-01',
    endDate: '2022-01-02',
  },
  {
    tournamentId: 3,
    name: 'Závody velkých holek',
    location: 'Třebíč',
    startDate: '2022-01-01',
    endDate: '2022-01-02',
  },
  {
    tournamentId: 4,
    name: 'Gymnastické závody',
    location: 'Zbraslavice',
    startDate: '2022-01-01',
    endDate: '2022-01-02',
  },
  {
    tournamentId: 5,
    name: 'Gymnastické závody mladých dívek',
    location: 'Zbraslavice',
    startDate: '2022-01-01',
    endDate: '2022-01-02',
  },
];

export const tournamentSports = [
  {
    tournamentId: 1,
    sportId: 1,
  },
  {
    tournamentId: 1,
    sportId: 2,
  },
];
